# Generated by Django 3.2 on 2023-12-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231130_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AlterField(
            model_name='model',
            name='slices',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.slice'),
        ),
        migrations.AlterField(
            model_name='model',
            name='statistics',
            field=models.ManyToManyField(blank=True, to='main.Statistic'),
        ),
    ]
