# Generated by Django 3.2 on 2023-12-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231204_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
